# Dark Restart Plugin Configuration

# Настройки рестарта
restart:
  countdown-sound: "block.note_block.pling"

# Авто рестарт настройки
auto-restart:
  enabled: true
  interval: 6 # Интервал между рестартами в часах
  warning-time: 300 # За сколько секунд начать предупреждать о рестарте
  warnings:
    - 300 # 5 минут
    - 240 # 4 минуты
    - 180 # 3 минуты
    - 120 # 2 минуты
    - 60  # 1 минута
    - 30  # 30 секунд
    - 10  # 10 секунд
    - 5   # 5 секунд

# Настройки уведомлений
notifications:
  actionbar: true
  sounds: true
  sound-volume: 1.0
  sound-pitch: 1.0

# Настройки меню
menu:
  title: "&9Меню рестарта"
  size: 27