# DarkRestart Configuration
restart:
  countdown-sound: "block.note_block.pling"
  warnings: [300, 60, 30, 10, 5] # предупреждения за 5,1,0.5,0.1,0.05 минут

notifications:
  actionbar: true
  sounds: true
  broadcast: true

auto-restart:
  enabled: false
  interval: 6