name: DarkRestart
version: 1.0.1
main: com.dark.restartplugin.RestartPlugin
api-version: 1.13
authors: [AuitDarkness]
description: Мощный плагин для управления рестартом сервера
website: https://github.com/AuitDarkness/DarkRestart
softdepend: [Vault]
commands:
  drestart:
    description: Основная команда плагина
    usage: /<command> [menu|start|cancel|status]
    aliases: [dr]
  autorestart:
    description: Команда управления авторестартом
    usage: /<command> [set|cancel|status]
    aliases: [ar]
permissions:
  darkrestart.admin:
    description: Полный доступ к плагину
    default: op
  darkrestart.moderator:
    description: Доступ к основным функциям
    default: op
  darkrestart.helper:
    description: Базовый доступ
    default: op
  darkrestart.use:
    description: Использование основных команд
    default: op
  darkrestart.autorestart:
    description: Управление авторестартом
    default: op
  darkrestart.technical:
    description: Доступ к техническому рестарту
    default: op
  darkrestart.notify:
    description: Получение уведомлений
    default: true